def cask(name); dep name, :template => "pzi:cask"; end # Avoid repitition below

cask "4k-video-downloader"
cask "adium"
cask "alfred"
cask "caffeine"
cask "cakebrew"
# cask "charles"
cask "firefox"
cask "dash"
cask "divvy"
cask "dropbox"
cask "fantastical"
cask "firefox"
# dep  "firefoxdeveloperedition", :template => "icelab:cask" do requires "icelab:homebrew tap".with "caskroom/versions" end
cask "fluid"
cask "flux"
cask "google-chrome"
cask "google-chrome-dev"
cask "gpgtools"
cask "hazel"
cask "imagealpha"
cask "imageoptim"
cask "iterm2"
cask "jumpcut"
cask "launchrocket"
cask "licecap"
cask "limechat"
cask "miro-video-converter"
cask "mou"
cask "namechanger"
cask "netspot"
cask "onepassword"
cask "qlcolorcode"
cask "qlstephen"
cask "quicklook-json"
cask "rdio"
cask "sitesucker"
cask "skype"
cask "slack"
cask "sourcetree"
cask "spectacle"
cask "spotify"
# dep "sublime-text3", :template => "icelab:cask" do requires "icelab:homebrew tap".with "caskroom/versions" end
cask "sublime-text3"
cask "superduper"
cask "the-unarchiver"
cask "things"
# cask "textexpander"
cask "transmission"
cask "transmit"
cask "virtualbox"
cask "vlc"
cask "webpquicklook"
