def cask(name); dep name, :template => "icelab:cask"; end # Avoid repitition below

cask "adium"
cask "alfred"
cask "caffeine"
# cask "charles"
cask "firefox"
cask "dash"
cask "divvy"
cask "dropbox"
cask "fantastical"
cask "firefox"
# dep  "firefoxdeveloperedition", :template => "icelab:cask" do requires "icelab:homebrew tap".with "caskroom/versions" end
cask "fluid"
cask "flux"
cask "google-chrome"
cask "google-chrome-dev"
cask "hazel"
cask "imagealpha"
cask "imageoptim"
cask "iterm2"
cask "licecap"
cask "limechat"
cask "miro-video-converter"
cask "mou"
cask "onepassword"
cask "rdio"
cask "skype"
cask "slack"
cask "sourcetree"
cask "spotify"
# dep "sublime-text3", :template => "icelab:cask" do requires "icelab:homebrew tap".with "caskroom/versions" end
cask "sublime-text3"
cask "superduper"
cask "the-unarchiver"
cask "things"
# cask "textexpander"
cask "transmission"
cask "transmit"
cask "virtualbox"
cask "vlc"
